# This file was auto-generated by MakeMake.py
CC=g++
CFLAGS=-std=c++11 -Wall -pedantic -g -ggdb -c

EXE_DIR=bin
TEST_DIR=asdasdasd
OBJ_DIR=bin/obj

EXE_NAME=the_program

INCLUDE_DIRS=-I include/SDL2 -I include/glew -I include/glm #-I include/FreeType2

LIB_DIRS=-L lib/glew -L lib/sdl2 #-L lib/FreeType2
LINK_COMMANDS=-lsdl2 -lopengl32 -lglew32 #-lfreetype2

COMPILE_WITH_CFLAGS=$(CC) $(CFLAGS)
COMPILE_WITH_INCLUDES=$(CC) $(CFLAGS) $(INCLUDE_DIRS)

OBJ_FILES=\
	$(OBJ_DIR)/Display.o\
	$(OBJ_DIR)/main.o\
	$(OBJ_DIR)/Drawable.o\
	$(OBJ_DIR)/Entity.o\
	$(OBJ_DIR)/EntityManager.o\
	$(OBJ_DIR)/Shader.o\
	$(OBJ_DIR)/LinkedList.o\
	$(OBJ_DIR)/MathUtil.o\
	$(OBJ_DIR)/Util.o

all: executable

executable: $(OBJ_FILES)
	$(CC) $(OBJ_FILES) -o $(EXE_DIR)/$(EXE_NAME) $(LIB_DIRS) $(LINK_COMMANDS)

$(OBJ_DIR)/Display.o: sauce/display/Display.cpp \
                      sauce/display/Display.h \
                      sauce/main/main.h \
                      sauce/model/EntityManager.h \
                      sauce/model/Entity.h \
                      sauce/util/containers/LinkedList.h
	$(COMPILE_WITH_INCLUDES) sauce/display/Display.cpp -o $(OBJ_DIR)/Display.o

$(OBJ_DIR)/main.o: sauce/main/main.cpp \
                   sauce/main/main.h \
                   sauce/model/EntityManager.h \
                   sauce/model/Entity.h \
                   sauce/util/containers/LinkedList.h \
                   sauce/display/Display.h \
                   sauce/model/Drawable.h \
                   sauce/model/Shader.h \
                   sauce/model/Shader.h
	$(COMPILE_WITH_INCLUDES) sauce/main/main.cpp -o $(OBJ_DIR)/main.o

$(OBJ_DIR)/Drawable.o: sauce/model/Drawable.cpp \
                       sauce/model/Drawable.h \
                       sauce/model/Entity.h \
                       sauce/model/Shader.h
	$(COMPILE_WITH_INCLUDES) sauce/model/Drawable.cpp -o $(OBJ_DIR)/Drawable.o

$(OBJ_DIR)/Entity.o: sauce/model/Entity.cpp \
                     sauce/main/main.h \
                     sauce/model/EntityManager.h \
                     sauce/model/Entity.h \
                     sauce/util/containers/LinkedList.h \
                     sauce/model/Entity.h
	$(COMPILE_WITH_INCLUDES) sauce/model/Entity.cpp -o $(OBJ_DIR)/Entity.o

$(OBJ_DIR)/EntityManager.o: \
                            sauce/model/EntityManager.cpp \
                            sauce/model/EntityManager.h \
                            sauce/model/Entity.h \
                            sauce/util/containers/LinkedList.h \
                            sauce/model/Drawable.h \
                            sauce/model/Shader.h
	$(COMPILE_WITH_INCLUDES) sauce/model/EntityManager.cpp -o $(OBJ_DIR)/EntityManager.o

$(OBJ_DIR)/Shader.o: sauce/model/Shader.cpp \
                     sauce/model/Shader.h
	$(COMPILE_WITH_INCLUDES) sauce/model/Shader.cpp -o $(OBJ_DIR)/Shader.o

$(OBJ_DIR)/LinkedList.o: \
                         sauce/util/containers/LinkedList.cpp \
                         sauce/util/containers/LinkedList.h
	$(COMPILE_WITH_INCLUDES) sauce/util/containers/LinkedList.cpp -o $(OBJ_DIR)/LinkedList.o

$(OBJ_DIR)/MathUtil.o: sauce/util/MathUtil.cpp \
                       sauce/util/MathUtil.h
	$(COMPILE_WITH_INCLUDES) sauce/util/MathUtil.cpp -o $(OBJ_DIR)/MathUtil.o

$(OBJ_DIR)/Util.o: sauce/util/Util.cpp \
                   sauce/util/Util.h
	$(COMPILE_WITH_INCLUDES) sauce/util/Util.cpp -o $(OBJ_DIR)/Util.o


# Run stuff
.PHONY: run
run:
	./$(EXE_DIR)/$(EXE_NAME)

.PHONY: runVal
runVal:
	valgrind ./$(EXE_DIR)/$(EXE_NAME)

# THIS IS A TEST OF IF IT WORKS LOL
# Clean
.PHONY: clean
clean:
	rm -rf $(OBJ_DIR)/*.o $(EXE_DIR)/$(EXE_NAME) $(EXE_DIR)/*.dll $(TEST_DIR)/* *~*

test:
	echo LOL

# Memes
.PHONY: urn
urn:
	@echo "You don't know how to make an urn."


.PHONY: rum
rum:
	@echo "Why is the rum gone?!"


.PHONY: ruin
ruin:
	@echo "You ruined it! :("


.PHONY: riun
riun:
	@echo "Dam dude... can't even ruin it right. :\\"


