# This file was auto-generated by MakeMake.py
CC=g++
CFLAGS=-std=c++11 -Wall -pedantic -g -ggdb -c

EXE_DIR=bin
TEST_DIR=bin/tests
OBJ_DIR=bin/obj

EXE_NAME=program

INCLUDE_DIRS= # Empty

LIB_DIRS= # Empty
LINK_COMMANDS= # Empty

COMPILE_WITH_CFLAGS=$(CC) $(CFLAGS)
COMPILE_WITH_INCLUDES=$(CC) $(CFLAGS) $(INCLUDE_DIRS)
OBJ_FILES=\
	$(OBJ_DIR)/empty.o\
	$(OBJ_DIR)/a.o\
	$(OBJ_DIR)/another_quite_long_file.o\
	$(OBJ_DIR)/b.o\
	$(OBJ_DIR)/really_long_filename_and_I_mean_really_long_line_longer_than_80_characters_long_lol.o\
	$(OBJ_DIR)/and_another_one.o\
	$(OBJ_DIR)/c.o


# Run stuff
.PHONY: run
run:
	./$(EXE_DIR)/$(EXE_NAME)

.PHONY: runVal
runVal:
	valgrind ./$(EXE_DIR)/$(EXE_NAME)


# Clean
.PHONY: clean
clean:
	rm -rf $(OBJ_DIR)/*.o $(EXE_DIR)/$(EXE_NAME) $(EXE_DIR)/*.dll $(TEST_DIR)/* *~*


# Memes
.PHONY: urn
urn:
	@echo "You don't know how to make an urn."


.PHONY: rum
rum:
	@echo "Why is the rum gone?!"


.PHONY: ruin
ruin:
	@echo "You ruined it! :("


.PHONY: riun
riun:
	@echo "Dam dude... can't even ruin it right. :\"
    
